name = "naveen"
print("Hello, " + name + "!")
print(name[2]) 
print(name.upper())
print(name.lower())
print(name.join("!!"))
print(name.find("a"))
print(name.replace("N","Pr"))
print(name.isupper())
print(name.islower())
print(name.endswith("n" ))
print(name.startswith("a"))
print(name.isalnum())
print(name.isdigit())